apiVersion: v1
kind: Pod
metadata:
  annotations:
    tier: loadBalancer
  name: nginx-pod
  labels:
    environment: production
    tier: backend
    appName: nginx
    team: development
spec:
  containers:
    - name: nginx-container
      image: nginx:1.27-alpine
