apiVersion: v1
kind: Pod
metadata:
  name: custom-multi-container-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sleep", "15"]
  containers:
    - name: nginx-container
      image: nginx
    - name: busybox-container
      image: busybox
      command: ["sleep"]
      args: ["60"]
