apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-nodejs-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-nodejs-app
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - default
