apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodejs-service
spec:
  selector:
    app: prometheus-nodejs-app
  ports:
    - name: http-metrics  # This is the port name
      protocol: TCP
      nodePort: 30004
      port: 4000       # Port that the service will expose
      targetPort: 4000  # Port that the container is listening on
  type: NodePort
